-- -*- coding: utf-8 -*-
-- Created by Luis Enrique Fuentes Plata

/* Creating XSMALL VWH.*/

USE CC_DW;

DROP WAREHOUSE TALEND_XS;

CREATE OR REPLACE WAREHOUSE TALEND_XS WITH
    WAREHOUSE_SIZE = XSMALL
    MAX_CLUSTER_COUNT = 2
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = ECONOMY --/Standard
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'XS Auto-Scale 2 nodes XSMALL';
    
USE WAREHOUSE TALEND_XS;